### ISSUE TITLE
apnotic v1.4.1 raise Exception `a block is needed when initializing an Apnotic::ConnectionPool`

### ISSUE THREAD

**Issue by hase1031** [yuki24/pushing#20]
```Apnotic::ConnectionPool``` of apnotic v1.4.0 needs some error handler as a block argument.
https://github.com/ostinelli/apnotic/pull/70
https://github.com/ostinelli/apnotic/commit/76418499e1052f719d21a419ef0e962d79761f97

**Comment by yuki24** [comment]
Yes, this is very important. I'll look to see if exceptions could be thrown properly and handled by Pushing's error handler.

**Comment by Stylo27** [comment]
@hase1031 
It's message raise because, Apnotic::ConnectionPool require a giving block 
https://github.com/ostinelli/apnotic/issues/71

**Comment by yuki24** [comment]
fixed by 7e245c4.
